version: "3"

services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    ports:
      - 9925:80
    environment:
      DB_TYPE: sqlite
      TZ: America/LosAngeles
    volumes:
      - ./data/:/app/data
    networks:
      - proxy
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.entrypoints=http"
      - "traefik.http.routers.mealie.rule=Host(`mealie.clay.sh`)"
      - "traefik.http.middlewares.mealie-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.mealie.middlewares=mealie-https-redirect"
      - "traefik.http.routers.mealie-secure.entrypoints=https"
      - "traefik.http.routers.mealie-secure.rule=Host(`mealie.clay.sh`)"
      - "traefik.http.routers.mealie-secure.tls=true"
      - "traefik.http.routers.mealie-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.mealie-secure.tls.domains[0].main=mealie.clay.sh"
      - "traefik.http.routers.mealie-secure.service=mealie"
      - "traefik.http.services.mealie.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
